### ISSUE TITLE
Links on PyPI don't work

### ISSUE THREAD

**Issue by cduvallet** [scienceforamerica/scipeds#1]
The links in the [PyPI readme](https://pypi.org/project/scipeds/) aren't redirecting to the full documentation site and instead are internal references that don't exist, eg [usage](https://pypi.org/project/scipeds/usage.ipynb/)

**Comment by chrisjkuch** [comment]
Closed by #2

**Comment by cduvallet** [comment]
Ah no, this is a different issue (that I am not sure how to fix). In the documentation, links to other pages in the document are referenced locally -- so the import of the README on PyPI keeps this and tries to link to an internal PyPI page which doesn't exist.
